//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MauiAppTemplate.Resources.Languages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MauiAppTemplate.Resources.Languages.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Principale.
        /// </summary>
        public static string Main_Tab {
            get {
                return ResourceManager.GetString("Main_Tab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Principale.
        /// </summary>
        public static string MainPage_Title {
            get {
                return ResourceManager.GetString("MainPage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paramètres.
        /// </summary>
        public static string Settings_Tab {
            get {
                return ResourceManager.GetString("Settings_Tab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sombre.
        /// </summary>
        public static string SettingsPage_DarkTheme {
            get {
                return ResourceManager.GetString("SettingsPage_DarkTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clair.
        /// </summary>
        public static string SettingsPage_LightTheme {
            get {
                return ResourceManager.GetString("SettingsPage_LightTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Système.
        /// </summary>
        public static string SettingsPage_SystemTheme {
            get {
                return ResourceManager.GetString("SettingsPage_SystemTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mes paramètres.
        /// </summary>
        public static string SettingsPage_Title {
            get {
                return ResourceManager.GetString("SettingsPage_Title", resourceCulture);
            }
        }
    }
}
